"""add snapshot timestamp

Revision ID: 093cc7a332fc
Revises: f1c51d31840b
Create Date: 2026-09-06 20:55:33.931795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093cc7a332fc'
down_revision: Union[str, Sequence[str], None] = 'f1c51d31840b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE pull_request_outcome
        SET lifecycle_status = COALESCE(lifecycle_status, status, 'pending'),
            outcome = COALESCE(outcome, 'uncertain')
        WHERE lifecycle_status IS NULL OR outcome IS NULL
        """
    )
    op.alter_column('pull_request_outcome', 'lifecycle_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pull_request_outcome', 'outcome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pull_request_outcome', 'outcome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pull_request_outcome', 'lifecycle_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
